# Generated by Django 2.2.3 on 2020-03-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
