# Generated by Django 2.2.3 on 2020-03-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofile',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='AgencyProfile',
        ),
        migrations.DeleteModel(
            name='TenantProfile',
        ),
    ]
