# Generated by Django 2.2.3 on 2020-04-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
