# Generated by Django 2.2.3 on 2020-03-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0002_auto_20200311_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
