# Generated by Django 2.2.3 on 2020-03-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0002_auto_20200327_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rate_my_agency.City'),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'tenant'), (2, 'agency'), (3, 'superuser')]),
        ),
    ]
