# Generated by Django 2.2.3 on 2020-03-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0003_auto_20200328_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='user',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='user',
            new_name='Name',
        ),
    ]
