# Generated by Django 2.2.3 on 2020-03-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0004_auto_20200330_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='Name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='Name',
            new_name='user',
        ),
    ]
