# Generated by Django 2.2.3 on 2020-03-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0005_auto_20200316_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rate_my_agency.Tenant')),
            ],
        ),
    ]
