# Generated by Django 2.2.3 on 2020-03-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0006_auto_20200330_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name',
        ),
    ]
