# Generated by Django 2.2.3 on 2020-03-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0008_auto_20200330_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='url',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='name',
        ),
        migrations.AddField(
            model_name='agency',
            name='agencyName',
            field=models.CharField(default='unnamed', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='cities',
            field=models.ManyToManyField(to='rate_my_agency.City'),
        ),
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
