# Generated by Django 2.2.3 on 2020-04-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0009_auto_20200331_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='agency_images')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_my_agency.Agency')),
            ],
        ),
    ]
