# Generated by Django 2.2.3 on 2020-04-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_my_agency', '0010_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agency_images/'),
        ),
    ]
